trigger:
- main

pool:
  name: Unity Windows Build Agents

steps:
# Build the Unity project to standalone. Since we are running on a Windows agent, this will produce
# an .exe executable and any dependency files needed.
- task: UnityBuildTask@3
  name: unitybuild
  inputs:
    buildTarget: 'standalone'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'untitled-game-build-win'

# Copy build output files to artifact staging directory.
- task: UnityBuildTask@3
  inputs:
    buildTarget: 'WebGL'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'untitled-game-build-web'

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.BinariesDirectory)
    Contents: '**'
    TargetFolder: $(Build.ArtifactStagingDirectory)
    CleanTargetFolder: true
    OverWrite: true

# Finally publish all items in artifact staging to the Azure Pipelines
# artifact storage. They will be available for sharing and/or further processing there.
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'untitled-game-build'
    publishLocation: 'Container'